/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.collections.map.HashedMap;


/**
 *
 * @author Nhi
 */
public class frmMain extends javax.swing.JFrame {
    public HoaDonBan mHoaDonBanPanel;
    public KhachHangPanel mKhachHangPanel;
    public CapNhatSanPhamPanel mSanPhamPanel;
    public ThongKePanel mThongKePanel;
 
 
    /**
     * Creates new form frmMain
     */
    private String dataMaTK;
    public frmMain() {
        
        initComponents();
        
        
         setLocationRelativeTo(null);
        
        //code full size
//        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);

    }

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnQLysanpham = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnQLyKhachHang = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnQLyHoaDonBH = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnThongKe = new javax.swing.JButton();
        TabbedPane1Main = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        Menu_Thoat = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BÁN HÀNG");
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoutt.png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(77, 70));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        btnQLysanpham.setBackground(new java.awt.Color(255, 255, 255));
        btnQLysanpham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLysanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sanpham1.png"))); // NOI18N
        btnQLysanpham.setText("Quản Lý Sản Phẩm");
        btnQLysanpham.setFocusable(false);
        btnQLysanpham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLysanpham.setMaximumSize(new java.awt.Dimension(180, 70));
        btnQLysanpham.setMinimumSize(new java.awt.Dimension(980, 21));
        btnQLysanpham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLysanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLysanphamActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLysanpham);
        jToolBar1.add(jSeparator7);

        btnQLyKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        btnQLyKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khachhang1.png"))); // NOI18N
        btnQLyKhachHang.setText("Quản Lý Khách Hàng");
        btnQLyKhachHang.setFocusable(false);
        btnQLyKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLyKhachHang.setMaximumSize(new java.awt.Dimension(180, 70));
        btnQLyKhachHang.setMinimumSize(new java.awt.Dimension(93, 21));
        btnQLyKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLyKhachHangMouseClicked(evt);
            }
        });
        btnQLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLyKhachHangActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLyKhachHang);
        jToolBar1.add(jSeparator5);

        btnQLyHoaDonBH.setBackground(new java.awt.Color(255, 255, 255));
        btnQLyHoaDonBH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQLyHoaDonBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/972617.png"))); // NOI18N
        btnQLyHoaDonBH.setText("Quản Lý Hóa Đơn");
        btnQLyHoaDonBH.setFocusable(false);
        btnQLyHoaDonBH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLyHoaDonBH.setMaximumSize(new java.awt.Dimension(180, 70));
        btnQLyHoaDonBH.setMinimumSize(new java.awt.Dimension(93, 21));
        btnQLyHoaDonBH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLyHoaDonBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLyHoaDonBHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLyHoaDonBH);
        jToolBar1.add(jSeparator4);

        btnThongKe.setBackground(new java.awt.Color(255, 255, 255));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/thongke1.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setMaximumSize(new java.awt.Dimension(180, 70));
        btnThongKe.setMinimumSize(new java.awt.Dimension(93, 21));
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));
        getContentPane().add(TabbedPane1Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 540));

        jLabel2.setBackground(new java.awt.Color(165, 186, 205));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(165, 186, 205));
        jLabel2.setText("Công ty TNHH giày thể thao GSneaker-Số 10, Đường Mễ Trì, Phường Mễ Trì, Quận  Nam Từ Liêm, Hà Nội, Việt Nam");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 640, 590, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/maxresdefault.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentShown(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1370, 690));

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenu5.setText("Đăng xuất");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jMenu1.add(jMenu5);

        Menu_Thoat.setText("Thoát");
        Menu_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ThoatMouseClicked(evt);
            }
        });
        Menu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ThoatActionPerformed(evt);
            }
        });
        jMenu1.add(Menu_Thoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý hệ thống");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sanpham2.png"))); // NOI18N
        jMenu6.setText("Quản lý sản phẩm");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/khachhang2.png"))); // NOI18N
        jMenu7.setText("Quản lý khách hàng");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/97261777.png"))); // NOI18N
        jMenu8.setText("Quản lý hóa đơn ");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ giúp");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jMenuItem1.setText("Giới thiệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnQLysanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLysanphamActionPerformed

        if (mSanPhamPanel==null) {
            mSanPhamPanel = new CapNhatSanPhamPanel();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/sanpham1.png"));
        TabbedPane1Main.addTab("Cập nhật thông tin sản phẩm",ic,mSanPhamPanel,"Cập nhật thông tin sản phẩm");
        }

        TabbedPane1Main.setSelectedComponent(mSanPhamPanel);
    }//GEN-LAST:event_btnQLysanphamActionPerformed

    private void Menu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ThoatActionPerformed
        
    }//GEN-LAST:event_Menu_ThoatActionPerformed

    private void Menu_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ThoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Menu_ThoatMouseClicked

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
//        TabbedPane1Main.removeAll();
        if (mThongKePanel==null) {
             mThongKePanel = new ThongKePanel();
            ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/thongke1.png"));
        TabbedPane1Main.addTab("Thống kê",ic,mThongKePanel,"Thống kê");
        }
           
        TabbedPane1Main.setSelectedComponent(mThongKePanel);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnQLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLyKhachHangActionPerformed
//        TabbedPane1Main.removeAll();
        if (mKhachHangPanel==null) {
             mKhachHangPanel = new KhachHangPanel();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/khachhang1.png"));
        TabbedPane1Main.addTab("Cập nhật thông tin khách hàng",ic,mKhachHangPanel,"Cập nhật thông tin khách hàng");
        }
        TabbedPane1Main.setSelectedComponent(mKhachHangPanel);
    }//GEN-LAST:event_btnQLyKhachHangActionPerformed

    private void btnQLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLyKhachHangMouseClicked
       
    }//GEN-LAST:event_btnQLyKhachHangMouseClicked

    private void btnQLyHoaDonBHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLyHoaDonBHActionPerformed
//        TabbedPane1Main.removeAll();
        if (mHoaDonBanPanel==null) {
            mHoaDonBanPanel = new HoaDonBan();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/972617.png"));
        TabbedPane1Main.addTab("Cập nhật hóa đơn bán",ic,mHoaDonBanPanel,"Cập nhật hóa đơn bán");
        }
        TabbedPane1Main.setSelectedComponent(mHoaDonBanPanel);
    }//GEN-LAST:event_btnQLyHoaDonBHActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GioiThieuDialog frDialog =new GioiThieuDialog(this,true);
        frDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Đăng xuất?","Đăng xuất khỏi hệ thống",
                                                JOptionPane.YES_NO_OPTION);
            if (res==JOptionPane.YES_OPTION) {
                this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                
                
                frmMain.this.dispose();
                frmMain.this.setEnabled(false);
                frmDangNhap dialog1 =   new frmDangNhap();
                dialog1.setVisible(true);
                frmMain.this.setEnabled(false);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        if (mSanPhamPanel==null) {
            mSanPhamPanel = new CapNhatSanPhamPanel();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/sanpham1.png"));
        TabbedPane1Main.addTab("Cập nhật thông tin sản phẩm",ic,mSanPhamPanel,"Cập nhật thông tin sản phẩm");
        }

        TabbedPane1Main.setSelectedComponent(mSanPhamPanel);
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        if (mSanPhamPanel==null) {
            mSanPhamPanel = new CapNhatSanPhamPanel();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/sanpham1.png"));
        TabbedPane1Main.addTab("Cập nhật thông tin sản phẩm",ic,mSanPhamPanel,"Cập nhật thông tin sản phẩm");
        }

        TabbedPane1Main.setSelectedComponent(mSanPhamPanel);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
         if (mKhachHangPanel==null) {
             mKhachHangPanel = new KhachHangPanel();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/khachhang1.png"));
        TabbedPane1Main.addTab("Cập nhật thông tin khách hàng",ic,mKhachHangPanel,"Cập nhật thông tin khách hàng");
        }
        TabbedPane1Main.setSelectedComponent(mKhachHangPanel);
    }//GEN-LAST:event_jMenu7MouseClicked

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        if (mHoaDonBanPanel==null) {
            mHoaDonBanPanel = new HoaDonBan();
        ImageIcon ic = new ImageIcon(getClass()
                .getResource("/icon/972617.png"));
        TabbedPane1Main.addTab("Cập nhật hóa đơn bán",ic,mHoaDonBanPanel,"Cập nhật hóa đơn bán");
        }
        TabbedPane1Main.setSelectedComponent(mHoaDonBanPanel);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jLabel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
//                new frmMain().setVisible(true);
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Thoat;
    private javax.swing.JTabbedPane TabbedPane1Main;
    private javax.swing.JButton btnQLyHoaDonBH;
    private javax.swing.JButton btnQLyKhachHang;
    private javax.swing.JButton btnQLysanpham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
